### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by ferib** [dword64/Ow-Outlines#2]
Hi, I noticed the VEH is not correctly simulating the instruction it is overwriting or the offset might be wrong.

The `Rip+3` doesn't match the size of the instruction at the given address, any chance your automated updating/pattern got broken? or that it should be offset by +`0x20`?

_(Asking for a friend ofc)_

**Comment by dword64** [comment]
@ferib will take a look on it :D

**Comment by dword64** [comment]
![image](https://user-images.githubusercontent.com/74870446/233812105-166ec62c-110b-4b13-8889-05e3e7ea91b2.png)
After taking a look it should work as wanted :D
